// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// dnn_delta_tanh
arma::mat dnn_delta_tanh(arma::mat W, arma::mat H, arma::mat delta);
RcppExport SEXP abcstats_dnn_delta_tanh(SEXP WSEXP, SEXP HSEXP, SEXP deltaSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< arma::mat >::type W(WSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type H(HSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type delta(deltaSEXP);
    __result = Rcpp::wrap(dnn_delta_tanh(W, H, delta));
    return __result;
END_RCPP
}
// dnn_tanh
arma::mat dnn_tanh(arma::mat W, arma::mat b, arma::mat x);
RcppExport SEXP abcstats_dnn_tanh(SEXP WSEXP, SEXP bSEXP, SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< arma::mat >::type W(WSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type b(bSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type x(xSEXP);
    __result = Rcpp::wrap(dnn_tanh(W, b, x));
    return __result;
END_RCPP
}
// dnn_lin
arma::mat dnn_lin(arma::mat W, arma::mat b, arma::mat x);
RcppExport SEXP abcstats_dnn_lin(SEXP WSEXP, SEXP bSEXP, SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< arma::mat >::type W(WSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type b(bSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type x(xSEXP);
    __result = Rcpp::wrap(dnn_lin(W, b, x));
    return __result;
END_RCPP
}
// dnn_predict
arma::mat dnn_predict(ListOf<NumericMatrix> Wbs, NumericMatrix x);
RcppExport SEXP abcstats_dnn_predict(SEXP WbsSEXP, SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< ListOf<NumericMatrix> >::type Wbs(WbsSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    __result = Rcpp::wrap(dnn_predict(Wbs, x));
    return __result;
END_RCPP
}
// dnn_grad
List dnn_grad(ListOf<NumericMatrix> Wbs, NumericMatrix x, NumericMatrix y);
RcppExport SEXP abcstats_dnn_grad(SEXP WbsSEXP, SEXP xSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< ListOf<NumericMatrix> >::type Wbs(WbsSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type y(ySEXP);
    __result = Rcpp::wrap(dnn_grad(Wbs, x, y));
    return __result;
END_RCPP
}
// ising_chain
NumericMatrix ising_chain(NumericMatrix x, double theta, int nits);
RcppExport SEXP abcstats_ising_chain(SEXP xSEXP, SEXP thetaSEXP, SEXP nitsSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< int >::type nits(nitsSEXP);
    __result = Rcpp::wrap(ising_chain(x, theta, nits));
    return __result;
END_RCPP
}
// fastPdist2
NumericMatrix fastPdist2(NumericMatrix Ar, NumericMatrix Br);
RcppExport SEXP abcstats_fastPdist2(SEXP ArSEXP, SEXP BrSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericMatrix >::type Ar(ArSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Br(BrSEXP);
    __result = Rcpp::wrap(fastPdist2(Ar, Br));
    return __result;
END_RCPP
}
// extract_mat
arma::mat extract_mat(ListOf<NumericMatrix> ll, int i);
RcppExport SEXP abcstats_extract_mat(SEXP llSEXP, SEXP iSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< ListOf<NumericMatrix> >::type ll(llSEXP);
    Rcpp::traits::input_parameter< int >::type i(iSEXP);
    __result = Rcpp::wrap(extract_mat(ll, i));
    return __result;
END_RCPP
}
