# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title Predict the output given a DNN and input matrix x
#' @param Ws Weight matrics of DNN, in a list
#' @param bs bias vectors of DNN, in a list
#' @param x Input, n x p matrix 
#' @param Hs A list to store intermediate results 
dnn_predict <- function(Ws, bs, x, Hs) {
    .Call('abcstats_dnn_predict', PACKAGE = 'abcstats', Ws, bs, x, Hs)
}

#' @title
#' fastPdist2
#' @description
#' Pairwise distance functions
#' 
#' @param Ar first matrix
#' 
#' @param Br second matrix
#' 
#' @details
#' \code{fastPdist} from http://blog.felixriedel.com/2013/05/pairwise-distances-in-r/
#'
#' @export
fastPdist2 <- function(Ar, Br) {
    .Call('abcstats_fastPdist2', PACKAGE = 'abcstats', Ar, Br)
}

