# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title Backprop subroutine for delta
#' @param W weight matrix
#' @param H H matrix
#' @param delta Input matrix 
dnn_delta_tanh <- function(W, H, delta) {
    .Call('abcstats_dnn_delta_tanh', PACKAGE = 'abcstats', W, H, delta)
}

#' @title Apply tanh function
#' @param W weight matrix
#' @param b bias matrix
#' @param x Input, n x p matrix 
dnn_tanh <- function(W, b, x) {
    .Call('abcstats_dnn_tanh', PACKAGE = 'abcstats', W, b, x)
}

#' @title Apply linear transform
#' @param W weight matrix
#' @param b bias matrix
#' @param x Input, n x p matrix 
dnn_lin <- function(W, b, x) {
    .Call('abcstats_dnn_lin', PACKAGE = 'abcstats', W, b, x)
}

#' @title Predict the output given a DNN and input matrix x
#' @param Wbs Weight matrics of DNN, in a list
#' @param x Input, n x p matrix 
dnn_predict <- function(Wbs, x) {
    .Call('abcstats_dnn_predict', PACKAGE = 'abcstats', Wbs, x)
}

#' @title Comput the gradient given a DNN and input matrix x, target y
#' @param Wbs Weight matrics of DNN, in a list
#' @param x Input, n x p matrix 
dnn_grad <- function(Wbs, x, y) {
    .Call('abcstats_dnn_grad', PACKAGE = 'abcstats', Wbs, x, y)
}

#' @title Runs MCMC on an Ising matrix
#' @param x Ising matrix
#' @param theta Ising parameter
#' @param nits Number of iterations
ising_chain <- function(x, theta, nits) {
    .Call('abcstats_ising_chain', PACKAGE = 'abcstats', x, theta, nits)
}

#' @title
#' fastPdist2
#' @description
#' Pairwise distance functions
#' 
#' @param Ar first matrix
#' 
#' @param Br second matrix
#' 
#' @details
#' \code{fastPdist} from http://blog.felixriedel.com/2013/05/pairwise-distances-in-r/
#'
#' @export
fastPdist2 <- function(Ar, Br) {
    .Call('abcstats_fastPdist2', PACKAGE = 'abcstats', Ar, Br)
}

#' @title Extract arma mat from list
#' @param ll List of NumericMatrix
#' @param i Index to extract
extract_mat <- function(ll, i) {
    .Call('abcstats_extract_mat', PACKAGE = 'abcstats', ll, i)
}

